# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe2101ca7f4839fbbec002996faecf217333d462e1c3b8743000c2f0ba7539fc333387c57cd99a6103a3c4245ca3af4d4e419639bd22f49b0016632933a2a7f8

test:
  secret_key_base: bf14bdbffa000b7e999b3cf4b0fc7e491b8fc29cb5e6fb5ae4dafac64d466929a67c84b38c48c8b9dc9b77ddf9b8195178a12a5bc30b278af4c71b7c00177fab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
